services:
    akeneo_connectivity.connection.persistence.query.select_connections:
        class: 'Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalSelectConnectionsQuery'
        arguments:
            - '@database_connection'

    akeneo_connectivity.connection.persistence.query.select_connection_with_credentials_by_code:
        class: 'Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalSelectConnectionWithCredentialsByCodeQuery'
        arguments:
            - '@database_connection'

    akeneo_connectivity.connection.persistence.query.select_connections_event_count_by_day:
        class: 'Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalSelectConnectionsEventCountByDayQuery'
        arguments:
            - '@database_connection'

    akeneo_connectivity.connection.persistence.query.extract_connections_product_event_count:
        class: Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalExtractConnectionsProductEventCountQuery
        arguments:
            - '@database_connection'
            - '%pim_catalog.entity.product.class%'

    akeneo_connectivity_connection.persistence.query.select_hourly_intervals_to_refresh:
        class: Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalSelectHourlyIntervalsToRefreshQuery
        arguments:
            - '@database_connection'

    akeneo_connectivity_connection.persistence.query.purge_audit_product:
        class: Akeneo\Connectivity\Connection\Infrastructure\Persistence\Dbal\Query\DbalPurgeAuditProductQuery
        arguments:
            - '@database_connection'
